version: 2

project_name: gitrespect

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/gitrespect
    binary: gitrespect
    ldflags:
      - -s -w -X github.com/juangracia/gitrespect/internal/cmd.Version={{.Version}} -X github.com/juangracia/gitrespect/internal/cmd.Commit={{.ShortCommit}} -X github.com/juangracia/gitrespect/internal/cmd.Date={{.Date}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

release:
  mode: replace

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

brews:
  - name: gitrespect
    repository:
      owner: juangracia
      name: homebrew-gitrespect
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/juangracia/gitrespect"
    description: "Respect your git work with real metrics. Measure AI productivity impact."
    license: "MIT"
    test: |
      system "#{bin}/gitrespect", "version"
    install: |
      bin.install "gitrespect"
